services:
  db:
    image: mysql:8.3
    container_name: smartvalidity-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: smartvalidity
      MYSQL_ROOT_PASSWORD: root
      TZ: America/Sao_Paulo
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: smartvalidity-app
    depends_on:
      - db
    restart: unless-stopped
    environment:
      DB_URL: jdbc:mysql://db:3306/smartvalidity?useSSL=false&serverTimezone=America/Sao_Paulo&useTimezone=true
      DB_USER: root
      DB_PWD: root
      SMTP_HOST: smtp.office365.com
      SMTP_PORT: 587
      SMTP_USERNAME: arthur.martins@alunos.sc.senac.br
      SMTP_PASSWORD: ${OUTLOOK_APP_PWD}
      TZ: America/Sao_Paulo
    ports:
      - "8080:8080"

volumes:
  db_data: 